
name: Validate Go

on:
  workflow_call:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Private repo access
      - name: Public repo access
        env:
          # use env vars to write unmasked secrets to .netrc file
          BUF_USER: ${{ secrets.BUF_USER }}
          BUF_TOKEN: ${{ secrets.BUF_PAT }}
          REPO_USER: ${{ secrets.REPO_USER }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          echo "
            machine github.com login $REPO_USER password $REPO_TOKEN
            machine buf.build login $BUF_USER password $BUF_PAT
          " >> ~/.netrc
      
      # alternative approach tom above
      # - run: |
      #     git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/


      # - name: Lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: latest

      - name: Unit tests
        run: |
          go env -w GOPRIVATE="github.com/${{ github.repository_owner }}/*"
          go mod download
          go test -tags jwx_es256k -v ./...
