name: Build and deploy static web app

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate version
        id: version
        uses: paulhatch/semantic-version@v5.0.2

      - name: npm config
        env:
          BUF_NPM_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: |
          echo "//buf.build/gen/npm/v1/:_authToken=$BUF_NPM_TOKEN" >> .npmrc

      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: /
          output_location: dist

      - name: Tag repo
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.version.outputs.version_tag }}",
              sha: context.sha
            })
